# Generated by Django 6.0.3 on 2026-03-07 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recovery_type', models.CharField(choices=[('alcohol', 'Alcohol'), ('substances', 'Substances'), ('smoking', 'Smoking'), ('gambling', 'Gambling'), ('other', 'Other'), ('private', 'Prefer not to say')], max_length=20)),
                ('avg_daily_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sobriety_start', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
